---
    - id: clang-format
      name: clang-format
      description: Format C code using clang-format.
      language: system
      files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
      entry: sh -c 'if [ -f .clang-format ]; then git ls-files | grep -E "\.(c|cc|cxx|cpp|h|hpp|hxx)$" | sed "s/.*/\"&\"/" | xargs clang-format -i -style=file;
          else git ls-files | grep -E "\.(c|cc|cxx|cpp|h|hpp|hxx)$" | sed "s/.*/\"&\"/" | xargs clang-format -i -style=Microsoft; fi'
      args: []
    - id: cppcheck
      name: cppcheck
      description: Check correctness of C code using cppcheck.
      language: system
      files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
      entry: cppcheck --error-exitcode=1
      args: [--enable=warning]
    - id: hlint
      name: hlint
      description: Haskell code checker. It gives suggestions to improve code.
      language: system
      files: \.hs$
      entry: hlint .
      args: []
    - id: fourmolu
      name: fourmolu
      description: Haskell code formatter.
      language: system
      files: \.hs$
      entry: fourmolu -i .
      args: []