---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-json
          - id: pretty-format-json
          - id: end-of-file-fixer
          - id: sort-simple-yaml
          - id: trailing-whitespace
          - id: check-added-large-files
          - id: check-yaml
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
