---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-json
          - id: pretty-format-json
          - id: end-of-file-fixer
          - id: sort-simple-yaml
          - id: trailing-whitespace
          - id: check-added-large-files
          - id: check-yaml
          - id: check-ast
          - id: name-tests-test
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
    - repo: https://github.com/AleksaC/hadolint-py
      rev: v2.12.0.3
      hooks:
          - id: hadolint
            args: [--ignore, DL3025, --ignore, DL3018, --ignore, DL3008, --ignore, DL3013]
    - repo: https://github.com/asottile/reorder-python-imports
      rev: v3.12.0
      hooks:
          - id: reorder-python-imports
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.3.0
      hooks:
          - id: ruff
          - id: ruff-format
