---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: end-of-file-fixer
          - id: sort-simple-yaml
          - id: check-added-large-files
          - id: trailing-whitespace
          - id: check-yaml
          - id: check-json
          - id: pretty-format-json
            args: [--autofix, --indent, '4', --no-sort-keys]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
    - repo: https://github.com/AleksaC/hadolint-py
      rev: v2.12.0.3
      hooks:
          - id: hadolint
            args: [--ignore, DL3025, --ignore, DL3018, --ignore, DL3008, --ignore, DL3013]
    - repo: https://github.com/ItsZcx/pre-commit-hooks
      rev: v1.4.0
      hooks:
          - id: clang-format
          - id: cppcheck
